Repository cloudposse/terraform-artifactory-kv-store, pull requests merged in 2024-05, with the labels that each got.

#11 chore: refactor to use context provider
  artifactory.tf
  context.tf
  examples/complete/context.tf
  examples/complete/fixtures.us-east-2.tfvars
  examples/complete/main.tf
  examples/complete/outputs.tf
  examples/complete/providers.tf
  examples/complete/variables.tf
  examples/complete/versions.tf
  main.tf
  outputs.tf
  test/src/examples_complete_test.go
  test/src/go.sum
  variables.tf
  versions.tf
Labels: triage

#6 feat: initial implementation
  README.md
  README.yaml
  artifactory.tf
  context.tf
  docs/terraform.md
  examples/complete/context.tf
  examples/complete/fixtures.us-east-2.tfvars
  examples/complete/main.tf
  examples/complete/outputs.tf
  examples/complete/providers.tf
  examples/complete/variables.tf
  examples/complete/versions.tf
  main.tf
  outputs.tf
  test/src/examples_complete_test.go
  test/src/go.sum
  variables.tf
  versions.tf
Labels: triage

#12 fix readme
  README.md
  docs/terraform.md
Labels: triage

#13 fix readme badges
  README.md
  README.yaml
Labels: no-release, triage

#14 Update GitHub Workflows to Fix ReviewDog TFLint Action
  .github/workflows/feature-branch.yml
Labels: auto-update, no-release, migration

#15 Update GitHub Workflows to use shared workflows from '.github' repo
  .github/workflows/branch.yml
  .github/workflows/chatops.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-published.yml
  .github/workflows/release.yml
  .github/workflows/scheduled.yml
Labels: auto-update, no-release, migration

#16 Update release workflow to allow pull-requests: write
  .github/workflows/release.yml
Labels: auto-update, no-release, migration
